# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\")\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1b\n\x0bItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"-\n\x0eSetItemRequest\x12\x1b\n\x04item\x18\x01 \x01(\x0b\x32\r.catalog.Item\"+\n\x0cItemResponse\x12\x1b\n\x04item\x18\x01 \x01(\x0b\x32\r.catalog.Item\"\x1d\n\x0cItemsRequest\x12\r\n\x05names\x18\x01 \x03(\t\"/\n\x0fSetItemsRequest\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.catalog.Item\"-\n\rItemsResponse\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.catalog.Item2\x99\x04\n\x0e\x43\x61talogManager\x12\x38\n\x07GetItem\x12\x14.catalog.ItemRequest\x1a\x15.catalog.ItemResponse\"\x00\x12;\n\x07SetItem\x12\x17.catalog.SetItemRequest\x1a\x15.catalog.ItemResponse\"\x00\x12;\n\nDeleteItem\x12\x14.catalog.ItemRequest\x1a\x15.catalog.ItemResponse\"\x00\x12;\n\x08GetItems\x12\x15.catalog.ItemsRequest\x1a\x16.catalog.ItemsResponse\"\x00\x12>\n\x08SetItems\x12\x18.catalog.SetItemsRequest\x1a\x16.catalog.ItemsResponse\"\x00\x12>\n\x0b\x44\x65leteItems\x12\x15.catalog.ItemsRequest\x1a\x16.catalog.ItemsResponse\"\x00\x12\x44\n\x10GetItemsAsStream\x12\x15.catalog.ItemsRequest\x1a\x15.catalog.ItemResponse\"\x00\x30\x01\x12P\n\x1bGetItemsAsStreamInteractive\x12\x14.catalog.ItemRequest\x1a\x15.catalog.ItemResponse\"\x00(\x01\x30\x01\x42\x39Z7github.com/dknlam/grpc_playground/catalog/catalog_protob\x06proto3')



_ITEM = DESCRIPTOR.message_types_by_name['Item']
_ITEMREQUEST = DESCRIPTOR.message_types_by_name['ItemRequest']
_SETITEMREQUEST = DESCRIPTOR.message_types_by_name['SetItemRequest']
_ITEMRESPONSE = DESCRIPTOR.message_types_by_name['ItemResponse']
_ITEMSREQUEST = DESCRIPTOR.message_types_by_name['ItemsRequest']
_SETITEMSREQUEST = DESCRIPTOR.message_types_by_name['SetItemsRequest']
_ITEMSRESPONSE = DESCRIPTOR.message_types_by_name['ItemsResponse']
Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.Item)
  })
_sym_db.RegisterMessage(Item)

ItemRequest = _reflection.GeneratedProtocolMessageType('ItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.ItemRequest)
  })
_sym_db.RegisterMessage(ItemRequest)

SetItemRequest = _reflection.GeneratedProtocolMessageType('SetItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETITEMREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.SetItemRequest)
  })
_sym_db.RegisterMessage(SetItemRequest)

ItemResponse = _reflection.GeneratedProtocolMessageType('ItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _ITEMRESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.ItemResponse)
  })
_sym_db.RegisterMessage(ItemResponse)

ItemsRequest = _reflection.GeneratedProtocolMessageType('ItemsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.ItemsRequest)
  })
_sym_db.RegisterMessage(ItemsRequest)

SetItemsRequest = _reflection.GeneratedProtocolMessageType('SetItemsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETITEMSREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.SetItemsRequest)
  })
_sym_db.RegisterMessage(SetItemsRequest)

ItemsResponse = _reflection.GeneratedProtocolMessageType('ItemsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSRESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:catalog.ItemsResponse)
  })
_sym_db.RegisterMessage(ItemsResponse)

_CATALOGMANAGER = DESCRIPTOR.services_by_name['CatalogManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/dknlam/grpc_playground/catalog/catalog_proto'
  _ITEM._serialized_start=26
  _ITEM._serialized_end=67
  _ITEMREQUEST._serialized_start=69
  _ITEMREQUEST._serialized_end=96
  _SETITEMREQUEST._serialized_start=98
  _SETITEMREQUEST._serialized_end=143
  _ITEMRESPONSE._serialized_start=145
  _ITEMRESPONSE._serialized_end=188
  _ITEMSREQUEST._serialized_start=190
  _ITEMSREQUEST._serialized_end=219
  _SETITEMSREQUEST._serialized_start=221
  _SETITEMSREQUEST._serialized_end=268
  _ITEMSRESPONSE._serialized_start=270
  _ITEMSRESPONSE._serialized_end=315
  _CATALOGMANAGER._serialized_start=318
  _CATALOGMANAGER._serialized_end=855
# @@protoc_insertion_point(module_scope)
